### PR TITLE
Add support for `keep_firing_for` in the parser

### PR DESCRIPTION
**Pull request by felipesere**
This has been merged into Prometheus, Prometheus Operator and is close to done in Thanos.

### CODE REVIEW

**Comment by prymitive** [comment]
Thanks.
Since this affects how long alerts fire and resolve `alerts/count` check will need to be updated to take it into account, like we do with `for` - https://github.com/cloudflare/pint/blob/main/internal/checks/alerts_count.go#L95

**Comment by felipesere** [comment]
I'm not sure how to exactly account for `keep_firing_for`. Does the AlertCount check verify how many "up-flanks" there were - i.e. change from pending to firing?
I wonder if I need to make we don't count any ranges that fall within `keep_firing_for` of an already counted alert?

**Comment by prymitive** [comment]
> I'm not sure how to exactly account for `keep_firing_for`. Does the AlertCount check verify how many "up-flanks" there were - i.e. change from pending to firing? I wonder if I need to make we don't count any ranges that fall within `keep_firing_for` of an already counted alert?

It simply walks over samples from Prometheus range query response.
This needs a lot more changes than just parsing, so I'll add tests for this in alerts/count + add the rest of needed changes.

**Comment by prymitive** [comment]
- [ ] alerts/count
- [ ] alerts/for
- [ ] rule/for
- [ ] config match

**Pull request merged**
